version: '3.8'

services:
  app:
    build: .
    container_name: smule-analytics-app
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=smule_db
      - FLASK_ENV=development
      - FLASK_APP=.
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: >
      sh -c "
        tail -f
      "

  db:
    image: postgres:11
    container_name: smule-analytics-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smule_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local