"""Initial migration

Revision ID: 7b5b0c7408cb
Revises: 
Create Date: 2025-03-22 18:09:25.057891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5b0c7408cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_cache',
    sa.Column('lat', sa.String(length=10), nullable=False),
    sa.Column('lon', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('lat', 'lon')
    )
    op.create_table('singer',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('performed_by', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('pic_url', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('singer_following',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('pic_url', sa.String(length=200), nullable=True),
    sa.Column('is_following', sa.Boolean(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('smule_list',
    sa.Column('list_type', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('list_type', 'item_name')
    )
    op.create_table('title_mapping',
    sa.Column('smule_title', sa.String(length=100), nullable=False),
    sa.Column('mapped_title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('smule_title')
    )
    op.create_table('title_metadata',
    sa.Column('fixed_title', sa.String(length=100), nullable=False),
    sa.Column('meta_title', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('duration', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rating_nbr', sa.Integer(), nullable=True),
    sa.Column('singer_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('fixed_title')
    )
    op.create_table('performance',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('ensemble_type', sa.String(length=10), nullable=True),
    sa.Column('perf_status', sa.String(length=1), nullable=True),
    sa.Column('child_count', sa.Integer(), nullable=True),
    sa.Column('app_uid', sa.String(length=20), nullable=True),
    sa.Column('arr_key', sa.String(length=30), nullable=True),
    sa.Column('orig_track_city', sa.String(length=40), nullable=True),
    sa.Column('orig_track_country', sa.String(length=40), nullable=True),
    sa.Column('media_url', sa.String(length=200), nullable=True),
    sa.Column('video_media_url', sa.String(length=200), nullable=True),
    sa.Column('video_media_mp4_url', sa.String(length=200), nullable=True),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=200), nullable=True),
    sa.Column('total_performers', sa.Integer(), nullable=True),
    sa.Column('total_listens', sa.Integer(), nullable=True),
    sa.Column('total_loves', sa.Integer(), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=True),
    sa.Column('total_commenters', sa.Integer(), nullable=True),
    sa.Column('performed_by', sa.String(length=50), nullable=True),
    sa.Column('performed_by_url', sa.String(length=50), nullable=True),
    sa.Column('owner_account_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_handle', sa.String(length=50), nullable=True),
    sa.Column('owner_pic_url', sa.String(length=200), nullable=True),
    sa.Column('owner_lat', sa.Float(), nullable=True),
    sa.Column('owner_lon', sa.Float(), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('performers', sa.String(length=100), nullable=True),
    sa.Column('performer_ids', sa.String(length=200), nullable=True),
    sa.Column('performer_handles', sa.String(length=200), nullable=True),
    sa.Column('fixed_title', sa.String(length=100), nullable=True),
    sa.Column('short_ind', sa.String(length=1), nullable=True),
    sa.Column('parent_key', sa.String(length=30), nullable=True),
    sa.Column('display_pic_url', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_account_id'], ['singer.account_id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('performance_favorite',
    sa.Column('favorited_by_username', sa.String(length=50), nullable=False),
    sa.Column('performance_key', sa.String(length=30), nullable=False),
    sa.Column('rating_nbr', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performance_key'], ['performance.key'], ),
    sa.PrimaryKeyConstraint('favorited_by_username', 'performance_key')
    )
    with op.batch_alter_table('performance_favorite', schema=None) as batch_op:
        batch_op.create_index('i_perffav_perfkey', ['performance_key'], unique=False)

    op.create_table('performance_singer',
    sa.Column('performance_key', sa.String(length=30), nullable=False),
    sa.Column('singer_account_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performance_key'], ['performance.key'], ),
    sa.ForeignKeyConstraint(['singer_account_id'], ['singer.account_id'], ),
    sa.PrimaryKeyConstraint('performance_key', 'singer_account_id')
    )
    with op.batch_alter_table('performance_singer', schema=None) as batch_op:
        batch_op.create_index('i_perfsinger_singer', ['singer_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_singer', schema=None) as batch_op:
        batch_op.drop_index('i_perfsinger_singer')

    op.drop_table('performance_singer')
    with op.batch_alter_table('performance_favorite', schema=None) as batch_op:
        batch_op.drop_index('i_perffav_perfkey')

    op.drop_table('performance_favorite')
    op.drop_table('performance')
    op.drop_table('title_metadata')
    op.drop_table('title_mapping')
    op.drop_table('smule_list')
    op.drop_table('singer_following')
    op.drop_table('singer')
    op.drop_table('geo_cache')
    # ### end Alembic commands ###
